# Redirect lib.rsbuild.dev to rslib.rs
[[redirects]]
from = "https://lib.rsbuild.dev/*"
to = "https://rslib.rs/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/404.html"
status = 404
