# Redirect lib.rsbuild.rs to rslib.rs
# [[redirects]]
# from = "https://lib.rsbuild.rs/*"
# to = "https://rslib.rs/:splat"
# status = 301
# force = true

[[redirects]]
from = "/*"
to = "/404.html"
status = 404
