packages:
  - 'website'
  - 'packages/*'
  - 'scripts/*'
  - 'tests/**'
  - 'examples/**'
  - '!**/compiled/**'
  - '!**/compile/**'
  - '!**/dist-types/**'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - 'core-js'
  - 'core-js-pure'
  - 'esbuild'
  - 'nx'
  - 'simple-git-hooks'

overrides:
  'zx>@types/node': '-'

strictPeerDependencies: false
autoInstallPeers: false
hoistPattern: []
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@5.7.2 || 6.3.1
  - '@reduxjs/toolkit@2.10.1'
  - reselect@5.1.1
