import os from 'node:os';
import path from 'node:path';
import type { ExeArch, ExePlatform } from '../types';

export const MIN_EXE_NODE_VERSION = '25.7.0';

const parseVersion = (version: string) => {
  const [major = 0, minor = 0, patch = 0] = version
    .replace(/^v/, '')
    .split('.')
    .map((value) => Number.parseInt(value, 10));

  return { major, minor, patch };
};

const compareVersions = (left: string, right: string) => {
  const leftVersion = parseVersion(left);
  const rightVersion = parseVersion(right);

  if (leftVersion.major !== rightVersion.major) {
    return leftVersion.major - rightVersion.major;
  }

  if (leftVersion.minor !== rightVersion.minor) {
    return leftVersion.minor - rightVersion.minor;
  }

  return leftVersion.patch - rightVersion.patch;
};

export const isExeSupportedNodeVersion = (
  version: string = process.versions.node,
): boolean => {
  return compareVersions(version, MIN_EXE_NODE_VERSION) >= 0;
};

export const assertSupportedExeNodeVersion = (
  version: string = process.versions.node,
): void => {
  if (isExeSupportedNodeVersion(version)) {
    return;
  }

  throw new Error(
    `"experiments.exe" requires Node.js >= ${MIN_EXE_NODE_VERSION}, but the current version is ${version}.`,
  );
};

export const assertSupportedExeRuntime = (
  versions: NodeJS.ProcessVersions & {
    bun?: string;
    deno?: string;
  } = process.versions as NodeJS.ProcessVersions & {
    bun?: string;
    deno?: string;
  },
): void => {
  if (versions.bun) {
    throw new Error(
      `"experiments.exe" uses the Node.js SEA workflow and requires Node.js. For Bun, run "bun build --compile" on the JavaScript entry file generated by Rslib.`,
    );
  }

  if (versions.deno) {
    throw new Error(
      `"experiments.exe" uses the Node.js SEA workflow and requires Node.js. For Deno, run "deno compile" on the JavaScript entry file generated by Rslib.`,
    );
  }

  assertSupportedExeNodeVersion(versions.node);
};

export const compareNodeVersions = (left: string, right: string): number => {
  return compareVersions(left, right);
};

export const normalizeNodeVersion = (
  version: string = process.versions.node,
): string => {
  return version.startsWith('v') ? version : `v${version}`;
};

export const getCurrentExePlatform = (): ExePlatform => {
  if (
    process.platform === 'darwin' ||
    process.platform === 'linux' ||
    process.platform === 'win32'
  ) {
    return process.platform;
  }

  throw new Error(
    `"experiments.exe" does not support platform "${process.platform}".`,
  );
};

export const getCurrentExeArch = (): ExeArch => {
  if (process.arch === 'x64' || process.arch === 'arm64') {
    return process.arch;
  }

  throw new Error(
    `"experiments.exe" does not support architecture "${process.arch}".`,
  );
};

export const getExeCacheDir = (): string => {
  if (process.platform === 'win32') {
    return path.join(
      process.env.LOCALAPPDATA ?? path.join(os.homedir(), 'AppData', 'Local'),
      'rslib',
      'sea',
    );
  }

  const xdgCacheHome =
    process.env.XDG_CACHE_HOME ?? path.join(os.homedir(), '.cache');
  return path.join(xdgCacheHome, 'rslib', 'sea');
};
