# https://github.com/stackblitz-labs/pkg.pr.new
name: Preview Release

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release'
        required: true
        default: 'main'

permissions:
  contents: read

jobs:
  preview:
    if: github.repository == 'web-infra-dev/rslib'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}

      - name: Install pnpm
        run: |
          npm install -g corepack@latest --force
          corepack enable

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          filters: |
            changed:
              - "packages/**"
              - "pnpm-lock.yaml"

      - name: Setup Node.js
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install Dependencies
        if: steps.changes.outputs.changed == 'true'
        run: pnpm install

      - name: Publish Preview
        if: steps.changes.outputs.changed == 'true'
        run: pnpx pkg-pr-new publish --compact --pnpm ./packages/*
