name: Reusable Test

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      node-version:
        required: true
        type: string
      task:
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: Git config
        if: ${{ inputs.runner == 'windows-latest' }}
        shell: bash
        run: |
          git config --system core.longpaths true

      - name: Install pnpm
        run: |
          npm install -g corepack@latest --force
          corepack enable

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          predicate-quantifier: 'every'
          filters: |
            changed:
              - "!**/*.md"
              - "!**/*.mdx"
              - "!**/_meta.json"
              - "!**/dictionary.txt"

      - name: Setup Node.js ${{ inputs.node-version }}
        if: ${{ steps.changes.outputs.changed == 'true' }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        if: ${{ steps.changes.outputs.changed == 'true' }}
        run: pnpm install

      - name: Type Check
        if: ${{ steps.changes.outputs.changed == 'true' && inputs.task == 'ut' }}
        run: pnpm run type-check

      - name: Unit Test
        if: ${{ steps.changes.outputs.changed == 'true' && inputs.task == 'ut' }}
        run: pnpm run test:unit

      - name: Integration Test (Rstest)
        if: ${{ steps.changes.outputs.changed == 'true' && inputs.task == 'integration' }}
        run: pnpm run test:integration

      - name: Integration Test For Executable (Rstest)
        if: ${{ steps.changes.outputs.changed == 'true' && inputs.task == 'integration-exe' }}
        run: pnpm run test:integration:exe

      - name: E2E Test (Playwright)
        if: ${{ steps.changes.outputs.changed == 'true' && inputs.task == 'e2e' }}
        run: pnpm run test:e2e
