name: Reusable Test

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      node-version:
        required: true
        type: string
      task:
        required: true
        type: string

permissions: {}

jobs:
  test:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 1

      - name: Git config
        if: ${{ inputs.runner == 'windows-latest' }}
        shell: bash
        run: |
          git config --system core.longpaths true

      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: changes
        with:
          predicate-quantifier: 'every'
          filters: |
            changed:
              - "!**/*.md"
              - "!**/*.mdx"
              - "!**/_meta.json"
              - "!**/dictionary.txt"

      - name: Setup Node.js ${{ inputs.node-version }}
        if: ${{ steps.changes.outputs.changed == 'true' }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ inputs.node-version }}
          package-manager-cache: false

      - name: Install pnpm
        if: ${{ steps.changes.outputs.changed == 'true' }}
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: true

      - name: Build
        if: ${{ steps.changes.outputs.changed == 'true' }}
        run: pnpm run build

      - name: Unit Test
        if: ${{ steps.changes.outputs.changed == 'true' && inputs.task == 'ut' }}
        run: pnpm run test:unit

      - name: Integration Test (Rstest)
        if: ${{ steps.changes.outputs.changed == 'true' && inputs.task == 'integration' }}
        run: pnpm run test:integration

      - name: Integration Test For Executable (Rstest)
        if: ${{ steps.changes.outputs.changed == 'true' && inputs.task == 'integration-exe' }}
        run: pnpm run test:integration:exe

      - name: E2E Test (Playwright)
        if: ${{ steps.changes.outputs.changed == 'true' && inputs.task == 'e2e' }}
        run: pnpm run test:e2e
