name: Test

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  ut:
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest]
        node-version: [22]
    uses: ./.github/workflows/reusable-test.yml
    with:
      runner: ${{ matrix.runner }}
      node-version: ${{ matrix.node-version }}
      task: ut

  integration:
    strategy:
      matrix:
        runner: [ubuntu-latest]
        node-version: [18, 22]
        include:
          - runner: windows-latest
            node-version: 22

    uses: ./.github/workflows/reusable-test.yml
    with:
      runner: ${{ matrix.runner }}
      node-version: ${{ matrix.node-version }}
      task: integration

  e2e:
    strategy:
      matrix:
        runner: [ubuntu-latest]
        node-version: [18, 22]
        include:
          - runner: windows-latest
            node-version: 22
    uses: ./.github/workflows/reusable-test.yml
    with:
      runner: ${{ matrix.runner }}
      node-version: ${{ matrix.node-version }}
      task: e2e
